# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="underground"
version="1.0.0"
displayName="Underground"
credits="Chlamydomonos"
authors="Chlamydomonos"
description='''
Underground survival
'''
[[dependencies.underground]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.underground]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
